# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconStatementPredicate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, edge_label: str=None, relation: str=None):  # noqa: E501
        """BeaconStatementPredicate - a model defined in Swagger

        :param edge_label: The edge_label of this BeaconStatementPredicate.  # noqa: E501
        :type edge_label: str
        :param relation: The relation of this BeaconStatementPredicate.  # noqa: E501
        :type relation: str
        """
        self.swagger_types = {
            'edge_label': str,
            'relation': str
        }

        self.attribute_map = {
            'edge_label': 'edge_label',
            'relation': 'relation'
        }

        self._edge_label = edge_label
        self._relation = relation

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconStatementPredicate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconStatementPredicate of this BeaconStatementPredicate.  # noqa: E501
        :rtype: BeaconStatementPredicate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_label(self) -> str:
        """Gets the edge_label of this BeaconStatementPredicate.

        minimal Biolink model predicate term  # noqa: E501

        :return: The edge_label of this BeaconStatementPredicate.
        :rtype: str
        """
        return self._edge_label

    @edge_label.setter
    def edge_label(self, edge_label: str):
        """Sets the edge_label of this BeaconStatementPredicate.

        minimal Biolink model predicate term  # noqa: E501

        :param edge_label: The edge_label of this BeaconStatementPredicate.
        :type edge_label: str
        """

        self._edge_label = edge_label

    @property
    def relation(self) -> str:
        """Gets the relation of this BeaconStatementPredicate.

        SHOULD be from maximal Biolink model predicate list, but beacon-specific extensions allowed. Preferred format is a CURIE, where one exists, but strings/labels acceptable. May be empty.  # noqa: E501

        :return: The relation of this BeaconStatementPredicate.
        :rtype: str
        """
        return self._relation

    @relation.setter
    def relation(self, relation: str):
        """Sets the relation of this BeaconStatementPredicate.

        SHOULD be from maximal Biolink model predicate list, but beacon-specific extensions allowed. Preferred format is a CURIE, where one exists, but strings/labels acceptable. May be empty.  # noqa: E501

        :param relation: The relation of this BeaconStatementPredicate.
        :type relation: str
        """

        self._relation = relation
