# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BeaconKnowledgeMapPredicate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, relation: str=None):  # noqa: E501
        """BeaconKnowledgeMapPredicate - a model defined in Swagger

        :param relation: The relation of this BeaconKnowledgeMapPredicate.  # noqa: E501
        :type relation: str
        """
        self.swagger_types = {
            'relation': str
        }

        self.attribute_map = {
            'relation': 'relation'
        }

        self._relation = relation

    @classmethod
    def from_dict(cls, dikt) -> 'BeaconKnowledgeMapPredicate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BeaconKnowledgeMapPredicate of this BeaconKnowledgeMapPredicate.  # noqa: E501
        :rtype: BeaconKnowledgeMapPredicate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def relation(self) -> str:
        """Gets the relation of this BeaconKnowledgeMapPredicate.

        Human readable name of the maximal given predicate relation. This should be specified as Biolink predicate names like  gene_associated_with_condition. See [Biolink Model](https://biolink.github.io/biolink-model) for the full list of terms   # noqa: E501

        :return: The relation of this BeaconKnowledgeMapPredicate.
        :rtype: str
        """
        return self._relation

    @relation.setter
    def relation(self, relation: str):
        """Sets the relation of this BeaconKnowledgeMapPredicate.

        Human readable name of the maximal given predicate relation. This should be specified as Biolink predicate names like  gene_associated_with_condition. See [Biolink Model](https://biolink.github.io/biolink-model) for the full list of terms   # noqa: E501

        :param relation: The relation of this BeaconKnowledgeMapPredicate.
        :type relation: str
        """

        self._relation = relation
